routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/cate_management', 'CategoryController');
Route::resource('/tag_management', 'TagController');
Route::resource('/post_management', 'PostController');
Route::get('/search', 'PostController@getSearch')->name('posts.search');

Route::group(['middleware' => 'auth'], function() {
});

Route::group( ['prefix' => 'admin','middleware' => ['auth', 'admin']], function() {
    Route::resource('/user_management','UserController');
});

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Http\Requests\PostRequest;

class Post extends Model
{
    protected $table = 'posts';
    protected $fillable = [
        'title',
        'summary',
        'content',
        'category_id',
        'user_id',
        'is_active',
        'cover',
    ];

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class, 'post_tag', 'post_id', 'tag_id');
    }

    public function findBy($id)
    {
        return $this->find($id);
    }

    public function getAll()
    {
        return $this->all();
    }

    public function getPaginate($perPage)
    {
        return $this->paginate($perPage);
    }

    public static function createPost(PostRequest $request)
    {
        $data = $request->all();
//        $data['cover'] = self::uploadFile($request->file('file'));
//        $data['user_id'] = auth()->check() ? auth()->user()->id : '';

        $post = Post::create($data);
//        $post->tags()->sync(request('tags'));

        return $post;
    }

    public static function updatePost(PostRequest $request, $id)
    {
        $data = $request->all();
        $data['cover'] = self::uploadFile($request->file('file'));
        $data['user_id'] = auth()->check() ? auth()->user()->id : '';

        $post = Post::find($id);
        $post->update($data);
        $post->tags()->sync(request('tags'));

        return $post;
    }

    public static function uploadFile($file)
    {
        $imageName = '';
        if ($file != null) {
            $image_name = $file->getClientOriginalName();
            $name = time() . "" . $image_name;
            $image_public_path = public_path("images");
            $file->move($image_public_path, $name);
            $imageName = "images/" . $name;
        }
        return $imageName;
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Post;
use App\Category;
use App\Tag;
use Illuminate\Http\Request;
use App\Http\Requests\PostRequest;


class PostController extends Controller
{
    protected $post, $category, $tag;

    public function __construct(Post $post, Category $category, Tag $tag)
    {
        $this->post = $post;
        $this->category = $category;
        $this->tag = $tag;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $Post = Post::with('category')->get();
        return view('post.list', compact('Post'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('post.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(PostRequest $request)
    {
        $this->post->createPost($request);
        return redirect()->route("post_management.index")->with('success','Post was create successful!');

    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = Post::find($id);
        $Category = Category::all();
        $Tag = Tag::all();
        return view('post.edit',compact('Category','post','Tag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(PostRequest $request, $id)
    {
        $this->post->updatePost($request, $id);
        return redirect()->route("post_management.index")->with('success','Post was updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        try {
            $post = Post::find($request->id);

            if ($post != null) {
                $post->delete();
                return response()->json(['status' => 1, 'message' => 'Deleted']);
            } else {
                return response()->json(['status' => 0, 'message' => 'Does not exit']);
            }
        } catch (\Exception $e) {
            $e->getMessage();
            return response()->json(['status' => 0, 'message' => 'Error']);
        }
    }

    public function getSearch(Request $request)
    {
        $post = Post::where('title', 'like', '%' . $request->key . '%')->get();
        return view('post.search', compact('post'));
    }
}

resources/views/post/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">

        @if(count($errors) > 0)
            <div class='alert alert-danger'>
                @foreach($errors->all() as $er)
                    <p>{{$er}}</p>
                @endforeach
            </div>
        @endif

        <form method="post" action="{{route('post_management.store')}}" enctype="multipart/form-data">
            @csrf
            <div class="form-group">
                <label for="name">Cover Image</label>
                <input type="file" class="form-control" id="file" name="file">
            </div>

            <div class="form-group">
                <label for="name">Title</label>
                <input type="text" class="form-control" id="title" name="title" placeholder="Enter Title">
            </div>

            <div class="form-group">
                <label for="name">Summary</label>
                <input type="text" class="form-control" id="summary" name="summary" placeholder="Enter summary">
            </div>

            <div class="form-group">
                <label for="name">Content</label>
                <textarea rows="6" cols="150" name="content"></textarea>
            </div>

{{--            <div class="form-group">--}}
{{--                <label for="name">Category</label>--}}
{{--                <select name="category_id" class="form-control">--}}
{{--                    @foreach($Category as $cate)--}}
{{--                        <option value="{{$cate->id}}">{{$cate->name}}</option>--}}
{{--                    @endforeach--}}
{{--                </select>--}}
{{--            </div>--}}

            <div class="form-group">
                <label for="name">Active</label>
                <select name="is_active" class="form-control">
                    <option value="0">Draft</option>
                    <option value="1">Publish</option>
                </select>
            </div>

{{--            <div class="field form-group">--}}
{{--                <label for="name" class="label">Tag</label>--}}
{{--                <select name="tags[]" multiple class="form-control">--}}
{{--                    @foreach($Tag as $tag)--}}
{{--                        <option value="{{$tag->id}}">{{$tag->name}}</option>--}}
{{--                    @endforeach--}}
{{--                </select>--}}
{{--            </div>--}}

            <button type="submit" class="btn btn-primary">Submit</button>

        </form>
    </div>

    <script>
        CKEDITOR.replace('content');
    </script>


@endsection

resources/views/post/edit.blade.php
@extends('layouts.app')

@section('content')
    <link rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
    <div class="container">

        @if(count($errors) > 0)
            <div class='alert alert-danger'>
                @foreach($errors->all() as $er)
                    <p>{{$er}}</p>
                @endforeach
            </div>
        @endif

        <form method="post" action="{{route('post_management.update', $post->id)}}" enctype="multipart/form-data">
            @method('PUT')
            @csrf
            <input type="hidden" name="id" value="{{$post->id}}">
            <div class="form-group">
                <label for="name">Cover Image</label>
                <input type="file" class="form-control" id="file" name="file" placeholder="Enter Title">
            </div>

            <div class="form-group">
                <label for="name">Title</label>
                <input type="text" class="form-control" id="title" name="title" placeholder="Enter Title"
                       value="{{$post->title}}">
            </div>

            <div class="form-group">
                <label for="name">Summary</label>
                <input type="text" class="form-control" id="summary" name="summary" placeholder="Enter summary"
                       value="{{$post->summary}}">
            </div>

            <div class="form-group">
                <label for="name">Content</label>
                <textarea rows="6" cols="150" name="content">{{$post->content}}</textarea>
            </div>

            <div class="form-group">
                <label for="name">Category</label>
                <select name="category" class="form-control">
                    @foreach($Category as $cate)
                        <option value="{{$cate->id}}"
                            {{$post->category_id == $cate->id ? 'selected' : ''}}
                        >{{$cate->name}}</option>
                    @endforeach
                </select>
            </div>

            <div class="form-group">
                <label for="name">Active</label>
                <select name="is_active" class="form-control">
                    <option value="0" {{$post->is_active == 0 ? 'selected' : ''}}>Draft</option>
                    <option value="1" {{$post->is_active == 1 ? 'selected' : ''}}>Publish</option>
                </select>
            </div>
            <div class="field form-group">
                <label for="name" class="label">Tag</label>
                <select name="tags[]" multiple class="form-control">
                    @foreach($Tag as $tag)
                        <option
                            value="{{$tag->id}}" {{$post->tag_id == $tag->id ? 'selected' : ''}}>{{$tag->name}}</option>
                    @endforeach
                </select>
            </div>


            <button type="submit" class="btn btn-primary">Submit</button>

        </form>
    </div>
    <script>
        CKEDITOR.replace('content');
    </script>
@endsection

resources/views/post/list.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>Post Manager</h1>

        @if (session('success'))
            <div class="flash-message">
                <p class="alert alert-success">{{Session('success')}}</p>
            </div>
        @endif

        <div style="font-size: 20pt"><a href="{{route('post_management.create')}}">Add new</a></div>

        <form action="{{url('/search')}}" role="search" method="get" id="searchform">
            <div class="row">
                <div class="col-sm-9 col-md-9 col-lg-9 col-xl-9">
                    <input type="text" id="post-title" name="key" class="form-control" placeholder="Enter title"/>
                </div>
                <div class="col-sm-3 col-md-3 col-lg-3 col-xl-3 text-right">
                    <button class="btn btn-success" type="submit" id="btnSearchPost">
                        <i class="fa fa-search mr-1"></i>Search
                    </button>
                </div>
            </div>
        </form>

        <div class="row mt-5" style="margin-top:20px;">
            <div class="col-md-12" id="postTable">
                <table class="table table-bordered">
                    <thead>
                    <tr style="background-color:rgb(215, 243, 227)" class="text-center">
                        <th>No.</th>
                        <th>Title</th>
                        <th>Summary</th>
                        <th>Category</th>
                        <th>Status</th>
                        <th>Tag</th>
                        <th>Action</th>

                    </tr>
                    </thead>
                    <tbody>
                    @foreach($Post as $post)
                        <tr class="text-center">
                            <td class="">{{$post->id}}</td>
                            <td class="title">{{$post->title}}</td>
                            <td class="summary">{{$post->summary}}</td>
                            <td class="category">{{optional($post->category)->name ?? ''}}</td>
                            <td class="status">{{$post->is_active == 1 ? 'Publish' : 'Draft'}}</td>
{{--                            <td class="tag">--}}
{{--                                @foreach($post->tags as $tag)--}}
{{--                                    {{$tag->name}}--}}
{{--                                @endforeach--}}
{{--                            </td>--}}

                            <td class="text-center">
                                <a href="{{route('post_management.edit', $post->id)}}">
                                <i class="fa fa-pencil-square-o text-success"></i></a>
                                <a onclick="delPost('{{$post->id}}')"><i class="fa fa-trash text-danger"></i></a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
{{--                {{$Post->links()}}--}}
            </div>
            @endsection

            @section('script')

                <script type="text/javascript" src="{{asset('js/post.js') }}"></script>
@endsection

resources/views/post/search.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>Post Manager</h1>

        <div class="flash-message">
            <p class="alert alert-success">{{Session::get('success')}}</p>
        </div>

        <div style="font-size: 20pt"><a href="{{route('post_management.create')}}">Add new</a></div>

        <form action="{{url('/search')}}" role="search" method="get" id="searchform">
            <div class="row">
                <div class="col-sm-9 col-md-9 col-lg-9 col-xl-9">
                    <input type="text" id="post-title" name="key" class="form-control" placeholder="Enter title"/>
                </div>
                <div class="col-sm-3 col-md-3 col-lg-3 col-xl-3 text-right">
                    <button class="btn btn-success" type="submit" id="btnSearchPost">
                        <i class="fa fa-search mr-1"></i>Search
                    </button>
                </div>
            </div>
        </form>

        <div class="row mt-5" style="margin-top:20px;">
            <div class="col-md-12" id="postTable">
                <table class="table table-bordered">
                    <thead>
                    <tr style="background-color:rgb(215, 243, 227)" class="text-center">
                        <th>No.</th>
                        <th>Title</th>
                        <th>Summary</th>
                        <th>Category</th>
                        <th>Status</th>
                        <th>Tag</th>
                        <th>Action</th>

                    </tr>
                    </thead>
                    <tbody>
                    @foreach($post as $p)
                        <tr class="text-center">
                            <td class="">{{$p->id}}</td>
                            <td class="title">{{$p->title}}</td>
                            <td class="summary">{{$p->summary}}</td>
                            <td class="category">{{optional($p->category)->name ?? ''}}</td>
                            <td class="status">{{$p->is_active == 1 ? 'Publish' : 'Draft'}}</td>
                            <td class="tag">
                                @foreach($p->tags as $tag)
                                    {{$tag->name}}
                                @endforeach
                            </td>

                            <td class="text-center">
                                <a href="{{route('post_management.edit', $p->id)}}"
                                <i class="fa fa-pencil-square-o text-success"></i></a>
                                <a onclick="delPost('{{$p->id}}')"><i class="fa fa-trash text-danger"></i></a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>
            @endsection

            @section('script')

                <script type="text/javascript" src="{{asset('js/post.js') }}"></script>
@endsection