routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/cate_management', 'CategoryController');
Route::resource('/tag_management', 'TagController');
Route::resource('/post_management', 'PostController');
Route::get('/search', 'PostController@getSearch')->name('posts.search');

Route::group(['middleware' => 'auth'], function() {
});

Route::group( ['prefix' => 'admin','middleware' => ['auth', 'admin']], function() {
    Route::resource('/user_management','UserController');
});

app/Category.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;
use App\Http\Requests\CategoryRequest;

class Category extends Model
{
    use SoftDeletes;

    protected $dates = ['deleted_at'];

    public function posts()
    {
        return $this->hasMany(Post::class, 'category_id', 'id');
    }

    public function findBy($id)
    {
        return $this->where('active',   1)->where('publish',   1)->find($id);
    }

    public function getAll()
    {
        return $this->all();
    }
}

app/Http/Controllers/CategoryController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use App\Repositories\CategoryRepository;
use Illuminate\Http\Request;
use App\Http\Requests\CategoryRequest;

class CategoryController extends Controller
{
    protected $category;
    protected $categoryRepository;

    public function __construct(Category $category, CategoryRepository $categoryRepository)
    {
        $this->category = $category;
        $this->categoryRepository = $categoryRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $Category = $this->category->all();
        return view('category.list',compact('Category'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('category.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        $this->categoryRepository->createCategory($request);
        return redirect()->route("cate_management.index")->with('success','Category added successful!');
    }

    /**
     * Display the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $cate = $this->category->find($id);
        return view('category.edit',compact('cate'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryRequest $request, $id)
    {
        $this->categoryRepository->updateCategory($request, $id);
        return redirect()->route("cate_management.index")->with('success','Category was updated!');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        try {
            $cate = $this->category->find($request->id);

            if ($cate != null) {
                $cate->delete();
                return response()->json(['status' => 1, 'message' => 'Deleted']);
            } else {
                return response()->json(['status' => 0, 'message' => 'Does not exit']);
            }
        } catch (\Exception $e) {
            $e->getMessage();
            return response()->json(['status' => 0, 'message' => 'Error']);
        }
    }
}

resources/views/category/create.blade.php
@extends('layouts.app');

@section('content')
    <div class="container">

        @if(count($errors) > 0)
            <div class='alert alert-danger'>
                @foreach($errors->all() as $er)
                    <p>{{$er}}</p>
                @endforeach
            </div>
        @endif

        <form method="post" action="{{route('cate_management.store')}}">
        <!-- <input type="hidden" name="_token" value="{{csrf_token()}}"> -->

            @csrf
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Enter Name">
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
@endsection

resources/views/category/edit.blade.php
@extends('layouts.app');

@section('content')
    <div class="container">

        @if(count($errors) > 0)
            <div class='alert alert-danger'>
                @foreach($errors->all() as $er)
                    <p>{{$er}}</p>
                @endforeach
            </div>
        @endif

        <form method="post" action="{{route('cate_management.update', $cate->id)}}">
        <!-- <input type="hidden" name="_token" value="{{csrf_token()}}"> -->

            @csrf
            <input type="hidden" name="_method" value="PUT">
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control" id="name" name="name"
                       placeholder="Enter Name" value="{{$cate->name}}">
            </div>

            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
@endsection

resources/views/category/list.blade.php
@extends('layouts.app')

@section('content')

    <div class="container">
        <h1>Category Manager</h1>
        @if (session('success'))
            <div class="flash-message">
                <p class="alert alert-success">{{Session('success')}}</p>
            </div>
        @endif
        <div style="font-size: 20pt"><a href="{{route('cate_management.create')}}">Add new</a></div>

        <div class="row mt-5" style="margin-top:20px;">
            <div class="col-md-12">
                <table class="table table-bordered">
                    <thead>
                    <tr style="background-color:rgb(215, 243, 227)">
                        <th class="text-center">No.</th>
                        <th class="text-center">Category Name</th>
                        <th class="text-center">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($Category as $cate)
                        <tr>
                            <td class="text-center">{{$cate->id}}</td>
                            <td class="name text-center">{{$cate->name}}</td>
                            <td class="text-center">
                                <a href="{{route('cate_management.edit', $cate->id)}}"> <i
                                        class="fa fa-pencil-square-o text-success"></i></a>
                                <a onclick="delCate('{{$cate->id}}')"><i class="fa fa-trash text-danger"></i></a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>

            @endsection
            @section('script')

                <script type="text/javascript" src="{{asset('js/category.js') }}"></script>
@endsection