routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/cate_management', 'CategoryController');
Route::resource('/tag_management', 'TagController');
Route::resource('/post_management', 'PostController');
Route::get('/search', 'PostController@getSearch')->name('posts.search');

Route::group(['middleware' => 'auth'], function() {
});

Route::group( ['prefix' => 'admin','middleware' => ['auth', 'admin']], function() {
    Route::resource('/user_management','UserController');
});

app/Tag.php
<?php

namespace App;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;
use App\Http\Requests\TagRequest;

class Tag extends Model
{
    public function posts()
    {
        return $this->belongsToMany(Post::class,'post_tag','tag_id','post_id');
    }

    public static function createTag(TagRequest $request)
    {
        $tag = new Tag();
        $tag->name = $request->name;
        $tag->created_at = Carbon::now();
        $tag->save();

        return $tag;
    }

    public static function updateTag(TagRequest $request, $id)
    {
        $tag = Tag::find($id);
        $tag->name = $request->name;
        $tag->save();

        return $tag;
    }
}

app/Http/Controllers/TagController.php
<?php

namespace App\Http\Controllers;

use App\Tag;
use Illuminate\Http\Request;
use App\Http\Requests\TagRequest;

class TagController extends Controller
{
    protected $tag;

    public function __construct(Tag $tag)
    {
        $this->tag = $tag;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $allTag = Tag::all();
        return view('tag.list',compact('allTag'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('tag.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TagRequest $request)
    {
        $this->tag->createTag($request);
        return redirect()->route("tag_management.index")->with('success','Tag added successful!');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $tag = Tag::find($id);
        return view('tag.edit',compact('tag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(TagRequest $request, $id)
    {
        $this->tag->updateTag($request, $id);
        return redirect()->route("tag_management.index")->with('success','Tag was updated!');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        try {
            $tag = Tag::find($request->id);

            if ($tag != null) {
                $tag->delete();
                return response()->json(['status' => 1, 'message' => 'Deleted']);
            } else {
                return response()->json(['status' => 0, 'message' => 'Does not exit']);
            }
        } catch (\Exception $e) {
            $e->getMessage();
            return response()->json(['status' => 0, 'message' => 'Error']);
        }
    }
}

resources/views/tag/create.blade.php
@extends('layouts.app');

@section('content')
    <div class="container">

        @if(count($errors) > 0)
            <div class='alert alert-danger'>
                @foreach($errors->all() as $er)
                    <p>{{$er}}</p>
                @endforeach
            </div>
        @endif

        <form method="post" action="{{route('tag_management.store')}}">
        <!-- <input type="hidden" name="_token" value="{{csrf_token()}}"> -->

            @csrf
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control" id="name" name="name" placeholder="Enter Name">
            </div>

            <button type="submit" class="btn btn-primary">Submit</button>
        </form>
    </div>
@endsection

resources/views/tag/edit.blade.php
@extends('layouts.app');

@section('content')
    <div class="container">

        @if(count($errors) > 0)
            <div class='alert alert-danger'>
                @foreach($errors->all() as $er)
                    <p>{{$er}}</p>
                @endforeach
            </div>
        @endif

        <form method="post" action="{{route('tag_management.update', $tag->id)}}">
        <!-- <input type="hidden" name="_token" value="{{csrf_token()}}"> -->

            @csrf
            <input type="hidden" name="_method" value="PUT">
            <div class="form-group">
                <label for="name">Name</label>
                <input type="text" class="form-control" id="name" name="name"
                       placeholder="Enter Name" value="{{$tag->name}}">
            </div>

            <button type="submit" class="btn btn-primary">Update</button>
        </form>
    </div>
@endsection

resources/views/tag/list.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <h1>Tag Manager</h1>
        @if (session('success'))
            <div class="flash-message">
                <p class="alert alert-success">{{Session('success')}}</p>
            </div>
        @endif
        <div style="font-size: 20pt"><a href="{{route('tag_management.create')}}">Add new</a></div>

        <div class="row mt-5" style="margin-top:20px;">
            <div class="col-md-12">
                <table class="table table-bordered">
                    <thead>
                    <tr style="background-color:rgb(215, 243, 227)">
                        <th class="text-center">No.</th>
                        <th class="text-center">Name</th>
                        <th class="text-center">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach($allTag as $tag)
                        <tr>
                            <td class="text-center">{{$tag->id}}</td>
                            <td class="name text-center">{{$tag->name}}</td>
                            <td class="text-center">
                                <a href="{{route('tag_management.edit', $tag->id)}}" <i
                                    class="fa fa-pencil-square-o text-success"></i></a>
                                <a onclick="delTag('{{$tag->id}}')"><i class="fa fa-trash text-danger"></i></a>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
            </div>


            @endsection

            @section('script')

                <script type="text/javascript" src="{{asset('js/tag.js') }}"></script>
@endsection